spring.application.name=per-translate-service

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:per_translate_service}
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Topics compatibles avec client-shell
application.topicout=${APPLICATION_TOPICOUT:topicout}
application.topicin=${APPLICATION_TOPICIN:topicin}

# LibreTranslate
libretranslate.url=${LIBRETRANSLATE_URL:http://localhost:5000/translate}
libretranslate.source=${LIBRETRANSLATE_SOURCE:auto}
libretranslate.target=${LIBRETRANSLATE_TARGET:fr}
libretranslate.format=${LIBRETRANSLATE_FORMAT:text}

# Logs
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=INFO
logging.level.org.isihop.fr.perTranslateService=INFO